import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const sfPro = localFont({
  src: [
    { path: './SF-Pro-Display-Regular.otf', weight: '400', style: 'normal' },
    { path: './SF-Pro-Display-Bold.otf', weight: '700', style: 'normal' },
    { path: './SF-Pro-Display-Semibold.otf', weight: '600', style: 'normal' },
  ],
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${sfPro.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
